// Created by iWeb 3.0.4 local-build-20150807

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,601),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_9.png'},{rect:new IWRect(1,-1,194,2),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_10.png'},{rect:new IWRect(195,-1,2,2),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_11.png'},{rect:new IWRect(195,1,2,601),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_12.png'},{rect:new IWRect(195,602,2,2),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_13.png'},{rect:new IWRect(1,602,194,2),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_14.png'},{rect:new IWRect(-1,602,2,2),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_15.png'}],new IWSize(196,603)),stroke_2:new IWEmptyStroke(),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,598),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_1.png'},{rect:new IWRect(1,-1,1010,2),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_2.png'},{rect:new IWRect(1011,-1,2,2),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_3.png'},{rect:new IWRect(1011,1,2,598),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_4.png'},{rect:new IWRect(1011,599,2,2),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_5.png'},{rect:new IWRect(1,599,1010,2),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_6.png'},{rect:new IWRect(-1,599,2,2),url:'Sara_Gutvill_-_Mezzosopraan_-_Babies_%26_Toddlers_files/stroke_7.png'}],new IWSize(1012,600))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Sara_Gutvill_-_Mezzosopraan_-_Babies_&_Toddlers_files/Sara_Gutvill_-_Mezzosopraan_-_Babies_&_ToddlersMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');fixAllIEPNGs('Media/transparent.gif');applyEffects()}
